# Enable gzip and brotli compression algorithms

gzip on;
gzip_min_length 1024; # Compress only responses larger than 1KB.
gzip_comp_level 5;
gzip_buffers 16 8k; # 16 buffers by 8kb = 128kb for one response.

# Compress responses even when proxied(from backend).
# By default nginx compress only with special headers.
gzip_proxied any;

# Content types eligible for gzip compression.
gzip_types
    text/plain
    text/css
    text/javascript
    application/javascript
    application/json
    application/xml
    application/rss+xml
    image/svg+xml;

# Accept encoding header.
gzip_vary on;

# Brotli(same logic above).

brotli on;
brotli_comp_level 5;
brotli_buffers 16 8k;

brotli_types
    text/plain
    text/css
    text/javascript
    application/javascript
    application/json
    application/xml
    image/svg+xml;