# Proxy settings with backend.

# Enable response buffering.
proxy_buffering on;
proxy_buffers 16 16k; # Buffer for response body.
proxy_buffer_size 16k; # Buffer for response headers.

# HTTP/1.1 used to support keep-alive and chunked requests.
proxy_http_version 1.1;
proxy_set_header Connection ""; # Do not allow nginx auto close connection.

# Timeout settings.
proxy_connect_timeout 5s; # Timeout for establishing connection to upstream.
proxy_send_timeout 30s; # Timeout for sending request to backend.
proxy_read_timeout 30s; # Timeout for reading response from upstream.

# Failover/retry logic.
# If backend returns something from pool below, try next server in upstream. 
proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
proxy_next_upstream_tries 3; # Maximum number of retry attempts.

# Forward client info.
# Send original host header to backend.
proxy_set_header Host $host;

# Send real client IP.
proxy_set_header X-Real-IP $remote_addr;

# Add client IP to X-Forwarded-For chain.
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

# Indicate original request protocol (HTTP or HTTPS).
proxy_set_header X-Forwarded-Proto $scheme; 
